name: CI

on:
  - pull_request
  - push

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tox_env:
          - py35
          - py36
          - py37
          - py38
          - py39
          - pypy3
    steps:
      - uses: actions/checkout@v2
      - uses: fedora-python/tox-github-action@v0.4
        with:
          tox_env: ${{matrix.tox_env}}
      - uses: actions/setup-python@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{runner.os}}-pip
      - run: |
          python -m pip install codecov
          codecov -X gcov
