name: test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tox_env:
          - py35
          - py36
          - py37
          - py38
          - py39
          - pypy3
    steps:
      - uses: actions/checkout@v2
      - uses: fedora-python/tox-github-action@v0.4
        with:
          tox_env: ${{ matrix.tox_env }}
      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
